const users = [
  {
    login: "dave",
    id: 925351,
    node_id: "MDQ6VXNlcjkyNTM1MQ==",
    avatar_url: "https://avatars.githubusercontent.com/u/925351?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/dave",
    html_url: "https://github.com/dave",
    followers_url: "https://api.github.com/users/dave/followers",
    following_url: "https://api.github.com/users/dave/following{/other_user}",
    gists_url: "https://api.github.com/users/dave/gists{/gist_id}",
    starred_url: "https://api.github.com/users/dave/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/dave/subscriptions",
    organizations_url: "https://api.github.com/users/dave/orgs",
    repos_url: "https://api.github.com/users/dave/repos",
    events_url: "https://api.github.com/users/dave/events{/privacy}",
    received_events_url: "https://api.github.com/users/dave/received_events",
    type: "User",
    site_admin: false,
    name: "Dave Brophy",
    company: null,
    blog: "https://www.wildernessprime.com/",
    location: null,
    email: null,
    hireable: null,
    bio: null,
    twitter_username: null,
    public_repos: 117,
    public_gists: 12,
    followers: 208,
    following: 1,
    created_at: "2011-07-19T13:04:55Z",
    updated_at: "2021-05-31T11:24:44Z",
  },
  {
    login: "john",
    id: 1668,
    node_id: "MDQ6VXNlcjE2Njg=",
    avatar_url: "https://avatars.githubusercontent.com/u/1668?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/john",
    html_url: "https://github.com/john",
    followers_url: "https://api.github.com/users/john/followers",
    following_url: "https://api.github.com/users/john/following{/other_user}",
    gists_url: "https://api.github.com/users/john/gists{/gist_id}",
    starred_url: "https://api.github.com/users/john/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/john/subscriptions",
    organizations_url: "https://api.github.com/users/john/orgs",
    repos_url: "https://api.github.com/users/john/repos",
    events_url: "https://api.github.com/users/john/events{/privacy}",
    received_events_url: "https://api.github.com/users/john/received_events",
    type: "User",
    site_admin: false,
    name: "John McGrath",
    company: "Amazon AWS",
    blog: "https://twitter.com/wordie",
    location: "San Francisco, CA",
    email: null,
    hireable: true,
    bio: "I'm on the sustainability team at AWS, and prior to that co-founded Entelo. Interested in renewable energy, journalism, startups, and democracy.",
    twitter_username: null,
    public_repos: 54,
    public_gists: 1,
    followers: 117,
    following: 48,
    created_at: "2008-02-28T23:17:13Z",
    updated_at: "2021-05-17T23:36:50Z",
  },
  {
    login: "lew",
    id: 42109,
    node_id: "MDQ6VXNlcjQyMTA5",
    avatar_url: "https://avatars.githubusercontent.com/u/42109?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/lew",
    html_url: "https://github.com/lew",
    followers_url: "https://api.github.com/users/lew/followers",
    following_url: "https://api.github.com/users/lew/following{/other_user}",
    gists_url: "https://api.github.com/users/lew/gists{/gist_id}",
    starred_url: "https://api.github.com/users/lew/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/lew/subscriptions",
    organizations_url: "https://api.github.com/users/lew/orgs",
    repos_url: "https://api.github.com/users/lew/repos",
    events_url: "https://api.github.com/users/lew/events{/privacy}",
    received_events_url: "https://api.github.com/users/lew/received_events",
    type: "User",
    site_admin: false,
    name: "Stefan Lew",
    company: null,
    blog: "stefanlew.com",
    location: "Linz, Austria",
    email: null,
    hireable: null,
    bio: null,
    twitter_username: null,
    public_repos: 8,
    public_gists: 1,
    followers: 7,
    following: 2,
    created_at: "2008-12-22T14:27:42Z",
    updated_at: "2021-05-17T15:42:31Z",
  },
  {
    login: "Karol",
    id: 2039656,
    node_id: "MDQ6VXNlcjIwMzk2NTY=",
    avatar_url: "https://avatars.githubusercontent.com/u/2039656?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Karol",
    html_url: "https://github.com/Karol",
    followers_url: "https://api.github.com/users/Karol/followers",
    following_url: "https://api.github.com/users/Karol/following{/other_user}",
    gists_url: "https://api.github.com/users/Karol/gists{/gist_id}",
    starred_url: "https://api.github.com/users/Karol/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/Karol/subscriptions",
    organizations_url: "https://api.github.com/users/Karol/orgs",
    repos_url: "https://api.github.com/users/Karol/repos",
    events_url: "https://api.github.com/users/Karol/events{/privacy}",
    received_events_url: "https://api.github.com/users/Karol/received_events",
    type: "User",
    site_admin: false,
    name: "Karol",
    company: "Systell",
    blog: "",
    location: "Poznań",
    email: null,
    hireable: null,
    bio: null,
    twitter_username: null,
    public_repos: 8,
    public_gists: 0,
    followers: 2,
    following: 0,
    created_at: "2012-07-25T10:11:49Z",
    updated_at: "2021-03-24T09:24:12Z",
  },
];

export { users };
